'use client';

import type { Payment, Tenant, Property } from '@/types';
import { formatCurrency } from '@/lib/utils';

interface Props {
  payment: Payment;
  tenant: Tenant;
  property: Property;
  invoiceNumber?: string;
}

export function RentInvoiceDocument({ payment, tenant, property, invoiceNumber }: Props) {
  const invNo = invoiceNumber || `INV-${payment.id.toUpperCase()}-${payment.date.replace(/-/g, '')}`;
  const dueDate = new Date(payment.date);
  dueDate.setDate(dueDate.getDate() + 5);

  return (
    <div className="max-w-[210mm] mx-auto bg-white p-8 print:p-0 text-sm text-gray-900 font-sans">
      <div className="flex justify-between items-start border-b-2 border-gray-900 pb-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold">RENT INVOICE</h1>
          <p className="text-lg font-semibold mt-1">RentFlow Kenya</p>
          <p className="text-xs text-gray-500">{property.location}</p>
          <p className="text-xs text-gray-500">{property.paymentInfo?.bankAccountName || 'Rent Payment'}</p>
        </div>
        <div className="text-right">
          <p className="text-xs text-gray-500">Invoice No:</p>
          <p className="font-bold">{invNo}</p>
          <p className="text-xs text-gray-500 mt-1">Date Issued:</p>
          <p className="font-semibold">{new Date(payment.date).toLocaleDateString('en-KE', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
        </div>
      </div>

      <div className="border border-gray-300 rounded-lg p-4 mb-6">
        <h2 className="font-bold text-sm mb-3">BILL TO</h2>
        <div className="grid grid-cols-2 gap-4 text-sm">
          <div><span className="text-gray-500">Tenant:</span><br /><span className="font-semibold">{tenant.name}</span></div>
          <div><span className="text-gray-500">ID Number:</span><br /><span className="font-semibold">{tenant.nationalId}</span></div>
          <div><span className="text-gray-500">Phone:</span><br /><span className="font-semibold">{tenant.phone}</span></div>
          <div><span className="text-gray-500">Email:</span><br /><span className="font-semibold">{tenant.email}</span></div>
          <div className="col-span-2"><span className="text-gray-500">Property:</span><br /><span className="font-semibold">{property.name}, Unit {payment.unitNumber}</span></div>
        </div>
      </div>

      <table className="w-full border-collapse mb-4">
        <thead>
          <tr className="border-b-2 border-gray-900">
            <th className="text-left py-2 text-xs uppercase text-gray-500 w-1/2">Description</th>
            <th className="text-center py-2 text-xs uppercase text-gray-500">Period</th>
            <th className="text-right py-2 text-xs uppercase text-gray-500">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-gray-200">
            <td className="py-3">Monthly Rent — Unit {payment.unitNumber}</td>
            <td className="py-3 text-center">{new Date(payment.date).toLocaleDateString('en-KE', { month: 'long', year: 'numeric' })}</td>
            <td className="py-3 text-right font-semibold">{formatCurrency(payment.amount)}</td>
          </tr>
        </tbody>
        <tfoot>
          <tr className="border-t-2 border-gray-900">
            <td colSpan={2} className="py-3 text-right font-bold text-base">TOTAL DUE</td>
            <td className="py-3 text-right font-bold text-lg">{formatCurrency(payment.amount)}</td>
          </tr>
        </tfoot>
      </table>

      <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 mb-6">
        <p className="text-xs text-amber-700">
          <strong>Payment Due Date:</strong> {dueDate.toLocaleDateString('en-KE', { day: '2-digit', month: 'long', year: 'numeric' })}.
          Late payment incurs a 5% penalty per month on outstanding amount.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4 text-sm mb-6">
        <div>
          <span className="text-gray-500">M-Pesa Paybill:</span>
          <p className="font-semibold">{property.paymentInfo?.mpesaPaybill || 'N/A'}</p>
          <p className="text-xs text-gray-500">Account: {tenant.nationalId}</p>
        </div>
        <div>
          <span className="text-gray-500">Bank Account:</span>
          <p className="font-semibold">{property.paymentInfo?.bankName || 'Bank'} — {property.paymentInfo?.bankAccount || 'N/A'}</p>
          <p className="text-xs text-gray-500">Branch: Nairobi, Kenya</p>
        </div>
      </div>

      <div className="border-t border-gray-300 pt-4 mt-4">
        <p className="text-xs text-gray-500 mb-1">Terms: Payment due within 5 days of invoice date.</p>
        <p className="text-xs text-gray-500 mb-1">For queries, please contact your property manager.</p>
      </div>

      <p className="text-[10px] text-gray-400 text-center mt-6">
        This is a computer-generated invoice. | Generated by RentFlow Kenya on {new Date().toLocaleString('en-KE')}
      </p>
    </div>
  );
}
